build: bump to Storybook 6.0.26
AxaFrance/react-toolkit pull request #700
Opened 2020-10-08 11:50 UTC by xballoy

- Upgrade Storybook from ~5.1.9 to 6.0.26
- Remove unused dependencies
- Bump dependencies to latest versions

Fixes #698

2020-10-09 09:11 UTC, xballoy commented
I will create another PR to migrate all the stories to CSF syntax. It's a lot of work, some stories need to be splitted (we test several components in the same story).

2020-10-11 06:54 UTC, arnaudforaison approved these changes, later dismissed
Great job @xballoy

2020-10-12 08:23 UTC, romuleald approved these changes, later dismissed
Top job

2020-10-12 08:25 UTC, youf-olivier commented
Je regarde ça

2020-10-12 08:49 UTC, youf-olivier commented
- Le datephone est KO
![image](https://user-images.githubusercontent.com/40664502/95725571-20c01480-0c78-11eb-9b16-db844f40ad28.png)

J'ai checké le reste tout semble ok 

Good Job 👏

2020-10-12 08:50 UTC, youf-olivier requested changes
DatePhone KO

2020-10-12 08:59 UTC, xballoy commented
@youf-olivier c'est corrigé, il fallait ajouter un paramètre `option: {}` sur toutes les stories et comme ce fichier là n'était pas bien formatté je ne l'avais pas vu quand j'ai fait une recherche...

2020-10-12 09:02 UTC, youf-olivier approved these changes

2020-10-12 10:10 UTC, arnaudforaison approved these changes

2020-10-12 10:10 UTC, merged