feat(design): fix some issues when a lot of texts is present
AxaFrance/react-toolkit pull request #996
Opened 2022-11-30 15:59 UTC by Cristallix

## Related issue

### Reference to the issue

Fix #995

### Description of the issue

The red vertical strip of the Alert component may be inconsistent depending of the content.

### Person(s) for reviewing proposed changes

None.

2023-01-03 13:38 UTC, samuel-gomez approved these changes

2023-02-06 10:45 UTC, Debaerdm approved these changes

2023-02-06 10:49 UTC, johankorger approved these changes

2023-02-06 10:50 UTC, Pirlouit approved these changes

2023-09-12 13:44 UTC, MartinWeb requested changes

2023-09-13 22:12 UTC, Cristallix commented on packages/alert/src/alert.scss
> +    font-size: 1.5rem;
Probablement ajouté par erreur quand j'ai fais mes modifications. J'ai annulé le changement.

2023-09-15 07:22 UTC, MartinWeb commented on packages/alert/src/alert.scss
>        &::after {
@samuel-gomez tu en penses quoi ?

2023-09-20 06:51 UTC, samuel-gomez-axa commented on packages/alert/src/alert.scss
>        &::after {
@MartinWeb en soit ça ne change pas la face du monde.
J'ai juste une question, c'est pourquoi ce changement ? il y avait une raison particulière de ne pas pouvoir rester iso ?

2023-09-21 08:34 UTC, samuel-gomez-axa commented on packages/alert/src/alert.scss
>        &::after {
@MartinWeb j'ai eu le retour de Rodney. C'est bien le résultat attendu :)
Il y a juste un dernier ajustement à faire : mettre la hauteur de l'icone à 20 et on sera tout bon

2023-09-21 08:35 UTC, samuel-gomez-axa approved these changes

2023-09-23 15:24 UTC, Cristallix commented on packages/alert/src/alert.scss
>        &::after {
Done.

2023-09-23 15:40 UTC, Railk commented on packages/alert/src/alert.scss
>        &::after {
vous pouvez me tagger directement avec mon compte github si besoin de retours UX ici :)

2023-09-28 15:21 UTC, samuel-gomez approved these changes

2023-10-09 09:52 UTC, MartinWeb approved these changes

2023-10-09 09:52 UTC, MartinWeb commented on packages/alert/src/alert.scss
>        &::after {
Super, merci à tous !

2023-10-09 09:52 UTC, merged